SELECT DISTINCT CITY
FROM STATION
WHERE (NOT(CITY LIKE 'A%' OR CITY  LIKE 'E%' OR CITY  LIKE 'I%' OR  CITY  LIKE 'O%' OR CITY  LIKE 'U%'))
OR
(NOT(CITY LIKE '%A' OR CITY LIKE '%E' OR CITY  LIKE '%I' OR CITY  LIKE '%O' OR CITY  LIKE '%U'))
ORDER BY CITY ;
